// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $api_ascents from "./routes/api/ascents.ts"
import * as $index from "./routes/index.tsx"
import * as $training_year_ from "./routes/training/[year].tsx"

import { type Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/ascents.ts": $api_ascents,
    "./routes/index.tsx": $index,
    "./routes/training/[year].tsx": $training_year_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
